# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9Z1-L4HVWqP6TGis8S12DODXvA757E6
"""

import matplotlib.pyplot as plt

x = [1, 2, 3, 4]

y= [10, 20, 25, 30]

plt.plot(x, y)



plt.title("Simple Line Graph")

plt.xlabel("X Axis")

plt.ylabel("Y Axis")

plt.show()