# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeiaCYPAe3H5HI42OhWb-ByhN50oqerp
"""

!pip install transformers -q

from transformers import pipeline

classifier = pipeline ("sentiment-analysis")

result = classifier ("I love learning AI!")

print(result)